# Generated by Django 5.2.4 on 2025-07-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_blogindexpage_careeradvicepage_homepage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta_url',
            field=models.CharField(blank=True, default='/', max_length=200),
        ),
    ]
