# Generated by Django 5.2.4 on 2025-07-12 20:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('soft_skills', 'Soft Skills'), ('language', 'Language'), ('certification', 'Certification'), ('tool', 'Tool/Software'), ('framework', 'Framework'), ('domain', 'Domain Knowledge')], default='technical', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('popularity_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('education_level', models.CharField(choices=[('high_school', 'High School'), ('associates', 'Associate Degree'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD/Doctorate'), ('certification', 'Professional Certification'), ('bootcamp', 'Bootcamp/Training Program')], default='bachelors', max_length=100)),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('current_role', models.CharField(blank=True, max_length=255, null=True)),
                ('current_company', models.CharField(blank=True, max_length=255, null=True)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('remote_work_preference', models.CharField(choices=[('on_site', 'On-site only'), ('remote', 'Remote only'), ('hybrid', 'Hybrid'), ('flexible', 'Flexible')], default='flexible', max_length=20)),
                ('career_interests', models.JSONField(blank=True, default=list)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('salary_expectations', models.JSONField(blank=True, default=dict)),
                ('profile_completed', models.BooleanField(default=False)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_size', models.CharField(blank=True, choices=[('startup', '1-10 employees'), ('small', '11-50 employees'), ('medium', '51-200 employees'), ('large', '201-1000 employees'), ('enterprise', '1000+ employees')], max_length=20, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('technologies_used', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('remote_work', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profiles.userprofile')),
            ],
            options={
                'db_table': 'user_experiences',
                'ordering': ['-is_current', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=255)),
                ('degree_type', models.CharField(choices=[('high_school', 'High School Diploma'), ('associates', 'Associate Degree'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD/Doctorate'), ('certification', 'Professional Certification'), ('bootcamp', 'Bootcamp'), ('online_course', 'Online Course')], max_length=50)),
                ('field_of_study', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('honors', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('relevant_coursework', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='profiles.userprofile')),
            ],
            options={
                'db_table': 'user_education',
                'ordering': ['-is_current', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.skill')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.userprofile')),
            ],
            options={
                'db_table': 'user_skills',
                'ordering': ['-is_primary', '-proficiency', 'skill__name'],
                'unique_together': {('user_profile', 'skill')},
            },
        ),
    ]
